### ISSUE TITLE
CSS 변수 사용하기

### ISSUE THREAD

**Issue by poby123** [egg-roll-1/egg-roll-Front#4]
https://developer.mozilla.org/ko/docs/Web/CSS/CSS_cascading_variables/Using_CSS_custom_properties

규칙 집합의 선택자는 사용자 지정 속성을 사용할 수 있는 범위를 정의합니다. 흔히 보이는 패턴은 [:root](https://developer.mozilla.org/ko/docs/Web/CSS/:root) 의사 클래스에 선언해서 여러분의 HTML 문서 어디에서나 사용자 지정 속성에 접근할 수 있도록 구성하는 것입니다.

```css
:root {
  --main-bg-color: brown;
}

element {
  background-color: var(--main-bg-color);
}
```
그러나 반드시 이렇게 선언해야 하는 것은 아닙니다. 범위를 제한해야 하는 적절한 이유가 있을 수도 있으니까요.
